



import {Montserrat, Poppins} from "next/font/google";
import "./globals.css";

// Component Import
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"

import AOSInitializer from "@/ui/AOSInitializer";

const montserrat = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-montserrat', // optional, for CSS usage
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {





  return (

    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <AOSInitializer/>
        <Navbar/>
        {/* <Navbar /> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
