



import { Jost, Outfit} from "next/font/google";
import "./globals.css";

// Component Import
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"

import AOSInitializer from "@/ui/AOSInitializer";
import ContactToggle from "@/ui/ContactToggle";

const montserrat = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-montserrat', // optional, for CSS usage
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

    robots: {
    index: false,
    follow: false,
  },
  // optional: also set this explicitly
  other: {
    'googlebot': 'noindex, nofollow',
  },
};

export default function RootLayout({ children }) {





  return (

    <html lang="en">
      <body className={`${montserrat.variable} antialiased relative`}>
        <AOSInitializer/>
        <Navbar/>
        <ContactToggle/>
        
        {/* <Navbar /> */} 
        {children}
        <Footer/>
      </body>
    </html>
  );
}
